# Generated by Django 4.0.2 on 2022-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('table', models.IntegerField(default=0)),
                ('tableSetNumber', models.IntegerField()),
                ('service', models.CharField(choices=[('Midi', 'Midi'), ('Soir', 'Soir')], default='Midi', max_length=4)),
            ],
        ),
    ]
